name: Update dataset repos
on:
  push:
    branches:
      - 'main'
jobs:
  update-dataset-repo:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fork:
          - neurodatascience/mr_proc-ppmi
          - neurodatascience/mr_proc-qpn
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ matrix.fork }}
      - name: Get upstream changes
        run: |
          git remote add upstream https://github.com/neurodatascience/mr_proc.git
          git fetch upstream main:upstream-main
          git reset --hard upstream-main
      - name: Create Pull Request
        id: step-create
        uses: peter-evans/create-pull-request@v4
        with:
          title: Update to match `neurodatascience/mr_proc:main`
          body: PR created/updated automatically by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action.
          token: ${{ secrets.PAT }}
          branch: main-upstream
      - name: Approve Pull Request
        if: ${{ steps.step-create.outputs.pull-request-number }}
        uses: michellewang/auto-approve-action@v3
        with:
          repository: ${{ matrix.fork }}
          pull-request-number: ${{ steps.step-create.outputs.pull-request-number }}
          review-message: PR approved by [auto-approve-action](https://github.com/michellewang/auto-approve-action) GitHub action.
          github-token: ${{ secrets.PAT2 }}
